using UnityEngine;
using UnityEngine.SceneManagement;
using Framework.ProcessMode;
using Framework.Dto;

/// <summary>
/// 测试 流程事件处理类
/// </summary>
public class 测试ProcessEvents : MonoBehaviour
{
    [ProcessAction]
    public void RegisterProcessEvents()
    {
        /// <summary>
        /// 步骤 1: 新步骤
        /// 动作 1: 新动作
        /// 目标对象: 对象1
        /// </summary>
        EventRegistrationCenter.AddEventsToAllStepEvents(new EventStepInfo(0, 0, "对象1", () =>
        {
            // 在这里加入事件处理逻辑
           Debug.Log("执行事件：步骤 1 -> 动作 1 -> 对象1");
        }));

        /// <summary>
        /// 步骤 1: 新步骤
        /// 动作 1: 新动作
        /// 目标对象: 对象2
        /// </summary>
        EventRegistrationCenter.AddEventsToAllStepEvents(new EventStepInfo(0, 0, "对象2", () =>
        {
            // 在这里加入事件处理逻辑
           Debug.Log("执行事件：步骤 1 -> 动作 1 -> 对象2");
        }));

    }
}
