using UnityEngine;
using UnityEngine.SceneManagement;
using Framework.ProcessMode;
using Framework.Dto;

/// <summary>
/// 新流程 流程事件处理类
/// </summary>
public class 新流程ProcessEvents : MonoBehaviour
{
    [ProcessAction]
    public void RegisterProcessEvents()
    {
        /// <summary>
        /// 步骤 1: 新步骤1
        /// 动作 1: 新动作11
        /// 目标对象: 草泥马
        /// </summary>
        EventRegistrationCenter.AddEventsToAllStepEvents(new EventStepInfo(0, 0, "草泥马", () =>
        {
            // 在这里加入事件处理逻辑
           Debug.Log("执行事件：步骤 1 -> 动作 1 -> 草泥马");
        }));

    }
}
