using System.Collections;
using Cysharp.Threading.Tasks;
using DefaultNamespace.Dto;
using Framework.Dto;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Framework.Test
{
    public class TestProcess : MonoBehaviour
    {
        // [ProcessAction]
        // public void RegisterProcessEvents()
        // {
        //     Debug.Log("注册事件：步骤 0 -> 动作 0 -> NPC(客户)1");
        //     //                                                                步骤编号    动作编号  目标名称         
        //     EventRegistrationCenter.AddEventsToAllStepEvents(new EventStepInfo(0, 0, "NPC(客户)1", () =>
        //     {
        //         Debug.Log("添加事件");
        //         // StartCoroutine(hahaha());
        //         SceneManager.LoadScene("2");
        //         hahaha();
        //     }));
        // }


        async void hahaha()
        {
            while (true)
            {
                for (int i = 0; i < 10; i++)
                {
                    Debug.Log(i);
                }

                await UniTask.Delay(1000);
            }
        }
    }
}