using System;
using System.Collections;
using System.Collections.Generic;
using MotionFramework;
using ToolsPack;
using UnityEngine;
using UnityEngine.Serialization;
using UnityEngine.UI;

public class ToolsPackWindowToggle : MonoBehaviour
{

    [SerializeField] private ModelTypeEnum modelTypeEnum;
    [SerializeField] private ToolsPackWindowManager _toolsPackWindowManager;
    private void Start()
    {
        // GameObject window =
        
        this.GetComponent<Toggle>().onValueChanged.AddListener((arg) =>
        {
            _toolsPackWindowManager.ChangePage(modelTypeEnum);
        });
        
    }

   
}